title: Y.A.B.
description: Mike Mondagon
url: "https://monde.github.io"
baseurl: ""

markdown: kramdown
permalink: /:year/:month/:day/:title/

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
